apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tasteless-cricket-nodejs 
  janus-idp.io/tekton: tasteless-cricket-nodejs
  backstage.io/kubernetes-id: tasteless-cricket-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-demo 
  app.kubernetes.io/part-of: tasteless-cricket-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  