apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tasteless-cricket-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tasteless-cricket-nodejs 
  name: tasteless-cricket-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tasteless-cricket-nodejs 
